### ISSUE TITLE
Broken while using bluebird 3

### ISSUE THREAD

**Issue by janpieterz** [KyleAMathews/superagent-bluebird-promise#37] opened 2015-10-29 13:37 UTC
When updating to bluebird 3 the package breaks:
http://bluebirdjs.com/docs/new-in-bluebird-3.html
and 
http://bluebirdjs.com/docs/api/cancellation.html

I don't have time to check it out further currently, just wanted to let you know.

**Comment by veke** [comment] 2015-11-09 14:01
Confirmed. This installs bluebird 3 as package dependency => not compatible

**Comment by janpieterz** [comment] 2015-11-09 14:11
@veke Until this library gets fixed I have a version that does work with version 3. @KyleAMathews I'd be more than happy to open a pull request if you're willing to break compatibility with <3

```js
// From https://gist.github.com/epeli/11209665

var Promise = require("bluebird");

// So you can `var request = require("superagent-bluebird-promise")`
var superagent = module.exports = require("superagent");
var Request = superagent.Request;

Promise.config({
    // Enable warnings.
    warnings: true,
    // Enable long stack traces.
    longStackTraces: true,
    // Enable cancellation.
    cancellation: true
});
// Create custom error type.
// Create a new object, that prototypally inherits from the Error constructor.
var SuperagentPromiseError = function(message, originalError) {
  var stack;
  this.message = message;
  this.name = 'SuperagentPromiseError';
  this.originalError = originalError;

  if (Error.captureStackTrace) {
    Error.captureStackTrace(this, this.constructor);
    stack = this.stack;
  }
  else {
    stack = (new Error(message)).stack;
  }

  if (Object.defineProperty) {
    Object.defineProperty(this, 'stack', {
      get: function() {
        if (this.originalError) {
          return stack + '\nCaused by:  ' + this.originalError.stack;
        }

        return stack;
      }
    });
  }
};

SuperagentPromiseError.prototype = new Error();
SuperagentPromiseError.prototype.constructor = SuperagentPromiseError;
superagent.SuperagentPromiseError = SuperagentPromiseError;

/**
 * @namespace utils
 * @class Superagent
 */

/**
 *
 * Add promise support for superagent/supertest
 *
 * Call .promise() to return promise for the request
 *
 * @method then
 * @return {Bluebird.Promise}
 */
Request.prototype.promise = function() {
  var req = this;
  var error;

  return new Promise(function(resolve, reject, onCancel) {
      req.end(function(err, res) {
        if (typeof res !== "undefined" && res.status >= 400) {
          var msg = 'cannot ' + req.method + ' ' + req.url + ' (' + res.status + ')';
          error = new SuperagentPromiseError(msg);
          error.status = res.status;
          error.body = res.body;
          error.res = res;
          reject(error);
        } else if (err) {
          reject(new SuperagentPromiseError('Bad request', err));
        } else {
          resolve(res);
        }
      });
      onCancel(function() {
           req.abort();
       });
    })
    .catch(Promise.CancellationError, function(err) {      
      req.abort();
      throw err;
    });
};

/**
 *
 * Make superagent requests Promises/A+ conformant
 *
 * Call .then([onFulfilled], [onRejected]) to register callbacks
 *
 * @method then
 * @param {function} [onFulfilled]
 * @param {function} [onRejected]
 * @return {Bluebird.Promise}
 */
Request.prototype.then = function() {
  var promise = this.promise();
  return promise.then.apply(promise, arguments);
};

```

**Comment by KyleAMathews** [comment] 2015-11-09 17:12
Yeah, a PR and a new major release would be great. Thanks!

**Comment by matthewgertner** [comment] 2015-11-16 09:50
+1 and BTW you definitely shouldn't use a `*` for the `peerDependencies` versions. This caused our app to break on our CI server as soon as Bluebird 3 came out. You should lock down the `peerDependencies` to a known compatible version.

**Comment by MMRandy** [comment] 2015-11-19 15:55
+1  What's the status of the PR, is this happening anytime soon?  Thx.

**Comment by janpieterz** [comment] 2015-11-20 06:17
A pull request has been opened here:
https://github.com/KyleAMathews/superagent-bluebird-promise/pull/42

**Comment by KyleAMathews** [comment] 2015-11-20 17:31
So as it turns out, this library was broken under Bluebird 2.9.x as well. I set the `peerDependency` for now to `2.8.x`. https://github.com/KyleAMathews/superagent-bluebird-promise/commit/b44fd4db7fbdc37e5694cc2a04945669668ec784

**Comment by MatthewPikar** [comment] 2015-12-20 17:20
+1 This would be great!

**Comment by heycalmdown** [comment] 2015-12-25 07:36
+1

**Comment by trueter** [comment] 2016-01-09 19:29
Lets make it happen.

**Comment by KyleAMathews** [comment] 2016-01-09 19:42
Forgot to close this. #42 was merged.

**Closed by KyleAMathews** 2016-01-09 19:42 UTC
